-- ── BSCS-4 Section 4A (batch_id=1, section_id=1, dept_id=1) ──
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) VALUES ('Ahmed Raza', 'ahmed.raza@student.edu', 'google_auth', 3);
INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) VALUES ((SELECT MAX(USER_ID) FROM USERS), 'BSCS-2022-010', 1, 1, 1, 3.85);
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) VALUES ('Sara Malik', 'sara.malik@student.edu', 'google_auth', 3);
INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) VALUES ((SELECT MAX(USER_ID) FROM USERS), 'BSCS-2022-011', 1, 1, 1, 3.72);
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) VALUES ('Usman Tariq', 'usman.tariq@student.edu', 'google_auth', 3);
INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) VALUES ((SELECT MAX(USER_ID) FROM USERS), 'BSCS-2022-012', 1, 1, 1, 3.55);
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) VALUES ('Fatima Khan', 'fatima.khan@student.edu', 'google_auth', 3);
INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) VALUES ((SELECT MAX(USER_ID) FROM USERS), 'BSCS-2022-013', 1, 1, 1, 3.20);
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) VALUES ('Ali Hassan', 'ali.hassan@student.edu', 'google_auth', 3);
INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) VALUES ((SELECT MAX(USER_ID) FROM USERS), 'BSCS-2022-014', 1, 1, 1, 3.91);

-- ── BSCS-4 Section 4B (batch_id=1, section_id=2, dept_id=1) ──
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) VALUES ('Zainab Hussain', 'zainab.hussain@student.edu', 'google_auth', 3);
INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) VALUES ((SELECT MAX(USER_ID) FROM USERS), 'BSCS-2022-020', 2, 1, 1, 3.78);
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) VALUES ('Hassan Shahid', 'hassan.shahid@student.edu', 'google_auth', 3);
INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) VALUES ((SELECT MAX(USER_ID) FROM USERS), 'BSCS-2022-021', 2, 1, 1, 3.60);
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) VALUES ('Amna Siddiqui', 'amna.siddiqui@student.edu', 'google_auth', 3);
INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) VALUES ((SELECT MAX(USER_ID) FROM USERS), 'BSCS-2022-022', 2, 1, 1, 3.95);
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) VALUES ('Bilal Ahmed', 'bilal.ahmed@student.edu', 'google_auth', 3);
INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) VALUES ((SELECT MAX(USER_ID) FROM USERS), 'BSCS-2022-023', 2, 1, 1, 2.95);
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) VALUES ('Hina Baig', 'hina.baig@student.edu', 'google_auth', 3);
INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) VALUES ((SELECT MAX(USER_ID) FROM USERS), 'BSCS-2022-024', 2, 1, 1, 3.68);

-- ── BSSE-4 Section 4A (batch_id=2, section_id=3, dept_id=2) ──
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) VALUES ('Nadia Farooq', 'nadia.farooq@student.edu', 'google_auth', 3);
INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) VALUES ((SELECT MAX(USER_ID) FROM USERS), 'BSSE-2022-010', 3, 2, 2, 3.88);
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) VALUES ('Omar Sheikh', 'omar.sheikh@student.edu', 'google_auth', 3);
INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) VALUES ((SELECT MAX(USER_ID) FROM USERS), 'BSSE-2022-011', 3, 2, 2, 3.52);
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) VALUES ('Rabia Noor', 'rabia.noor@student.edu', 'google_auth', 3);
INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) VALUES ((SELECT MAX(USER_ID) FROM USERS), 'BSSE-2022-012', 3, 2, 2, 3.75);
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) VALUES ('Kamran Iqbal', 'kamran.iqbal@student.edu', 'google_auth', 3);
INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) VALUES ((SELECT MAX(USER_ID) FROM USERS), 'BSSE-2022-013', 3, 2, 2, 2.80);
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) VALUES ('Sana Javed', 'sana.javed@student.edu', 'google_auth', 3);
INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) VALUES ((SELECT MAX(USER_ID) FROM USERS), 'BSSE-2022-014', 3, 2, 2, 3.92);

-- ── BSCS-3 Section 3A (batch_id=3, section_id=4, dept_id=1) ──
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) VALUES ('Tariq Mehmood', 'tariq.mehmood@student.edu', 'google_auth', 3);
INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) VALUES ((SELECT MAX(USER_ID) FROM USERS), 'BSCS-2023-010', 4, 3, 1, 3.65);
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) VALUES ('Maira Aziz', 'maira.aziz@student.edu', 'google_auth', 3);
INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) VALUES ((SELECT MAX(USER_ID) FROM USERS), 'BSCS-2023-011', 4, 3, 1, 3.80);
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) VALUES ('Faisal Rehman', 'faisal.rehman@student.edu', 'google_auth', 3);
INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) VALUES ((SELECT MAX(USER_ID) FROM USERS), 'BSCS-2023-012', 4, 3, 1, 2.70);
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) VALUES ('Ayesha Qureshi', 'ayesha.qureshi@student.edu', 'google_auth', 3);
INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) VALUES ((SELECT MAX(USER_ID) FROM USERS), 'BSCS-2023-013', 4, 3, 1, 3.58);
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) VALUES ('Imran Butt', 'imran.butt@student.edu', 'google_auth', 3);
INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) VALUES ((SELECT MAX(USER_ID) FROM USERS), 'BSCS-2023-014', 4, 3, 1, 3.71);

-- ── BSSE-3 Section 3A (batch_id=21, section_id=29, dept_id=2) ──
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) VALUES ('Sadia Perveen', 'sadia.perveen@student.edu', 'google_auth', 3);
INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) VALUES ((SELECT MAX(USER_ID) FROM USERS), 'BSSE-2023-010', 29, 21, 2, 3.88);
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) VALUES ('Waseem Akram', 'waseem.akram@student.edu', 'google_auth', 3);
INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) VALUES ((SELECT MAX(USER_ID) FROM USERS), 'BSSE-2023-011', 29, 21, 2, 3.55);
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) VALUES ('Lubna Rashid', 'lubna.rashid@student.edu', 'google_auth', 3);
INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) VALUES ((SELECT MAX(USER_ID) FROM USERS), 'BSSE-2023-012', 29, 21, 2, 2.90);
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) VALUES ('Adnan Malik', 'adnan.malik@student.edu', 'google_auth', 3);
INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) VALUES ((SELECT MAX(USER_ID) FROM USERS), 'BSSE-2023-013', 29, 21, 2, 3.76);
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) VALUES ('Rida Zafar', 'rida.zafar@student.edu', 'google_auth', 3);
INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) VALUES ((SELECT MAX(USER_ID) FROM USERS), 'BSSE-2023-014', 29, 21, 2, 3.62);

-- ── BSSE-3 Section 3B (batch_id=21, section_id=30, dept_id=2) ──
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) VALUES ('Zara Hussain', 'zara.hussain@student.edu', 'google_auth', 3);
INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) VALUES ((SELECT MAX(USER_ID) FROM USERS), 'BSSE-2023-020', 30, 21, 2, 3.90);
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) VALUES ('Hamza Nawaz', 'hamza.nawaz@student.edu', 'google_auth', 3);
INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) VALUES ((SELECT MAX(USER_ID) FROM USERS), 'BSSE-2023-021', 30, 21, 2, 3.51);
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) VALUES ('Maryam Ilyas', 'maryam.ilyas@student.edu', 'google_auth', 3);
INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) VALUES ((SELECT MAX(USER_ID) FROM USERS), 'BSSE-2023-022', 30, 21, 2, 2.65);
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) VALUES ('Shahzaib Khan', 'shahzaib.khan@student.edu', 'google_auth', 3);
INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) VALUES ((SELECT MAX(USER_ID) FROM USERS), 'BSSE-2023-023', 30, 21, 2, 3.83);
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) VALUES ('Iqra Nasir', 'iqra.nasir@student.edu', 'google_auth', 3);
INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) VALUES ((SELECT MAX(USER_ID) FROM USERS), 'BSSE-2023-024', 30, 21, 2, 3.69);

-- ── BSCS-2 Section 2A (batch_id=22, section_id=31, dept_id=1) ──
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) VALUES ('Nabeel Ahmed', 'nabeel.ahmed@student.edu', 'google_auth', 3);
INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) VALUES ((SELECT MAX(USER_ID) FROM USERS), 'BSCS-2024-010', 31, 22, 1, 3.77);
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) VALUES ('Huma Zubair', 'huma.zubair@student.edu', 'google_auth', 3);
INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) VALUES ((SELECT MAX(USER_ID) FROM USERS), 'BSCS-2024-011', 31, 22, 1, 3.56);
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) VALUES ('Danish Rauf', 'danish.rauf@student.edu', 'google_auth', 3);
INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) VALUES ((SELECT MAX(USER_ID) FROM USERS), 'BSCS-2024-012', 31, 22, 1, 2.88);
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) VALUES ('Asma Khalid', 'asma.khalid@student.edu', 'google_auth', 3);
INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) VALUES ((SELECT MAX(USER_ID) FROM USERS), 'BSCS-2024-013', 31, 22, 1, 3.93);
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) VALUES ('Umar Farooq', 'umar.farooq@student.edu', 'google_auth', 3);
INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) VALUES ((SELECT MAX(USER_ID) FROM USERS), 'BSCS-2024-014', 31, 22, 1, 3.64);

-- ── BSCS-2 Section 2B (batch_id=22, section_id=32, dept_id=1) ──
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) VALUES ('Saima Akhtar', 'saima.akhtar@student.edu', 'google_auth', 3);
INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) VALUES ((SELECT MAX(USER_ID) FROM USERS), 'BSCS-2024-020', 32, 22, 1, 3.82);
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) VALUES ('Junaid Aslam', 'junaid.aslam@student.edu', 'google_auth', 3);
INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) VALUES ((SELECT MAX(USER_ID) FROM USERS), 'BSCS-2024-021', 32, 22, 1, 3.53);
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) VALUES ('Mehwish Anwar', 'mehwish.anwar@student.edu', 'google_auth', 3);
INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) VALUES ((SELECT MAX(USER_ID) FROM USERS), 'BSCS-2024-022', 32, 22, 1, 2.75);
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) VALUES ('Taha Naseem', 'taha.naseem@student.edu', 'google_auth', 3);
INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) VALUES ((SELECT MAX(USER_ID) FROM USERS), 'BSCS-2024-023', 32, 22, 1, 3.70);
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) VALUES ('Rubab Zaman', 'rubab.zaman@student.edu', 'google_auth', 3);
INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) VALUES ((SELECT MAX(USER_ID) FROM USERS), 'BSCS-2024-024', 32, 22, 1, 3.87);

-- ── BSSE-2 Section 2A (batch_id=23, section_id=33, dept_id=2) ──
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) VALUES ('Areeba Sultan', 'areeba.sultan@student.edu', 'google_auth', 3);
INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) VALUES ((SELECT MAX(USER_ID) FROM USERS), 'BSSE-2024-010', 33, 23, 2, 3.79);
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) VALUES ('Owais Mirza', 'owais.mirza@student.edu', 'google_auth', 3);
INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) VALUES ((SELECT MAX(USER_ID) FROM USERS), 'BSSE-2024-011', 33, 23, 2, 3.57);
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) VALUES ('Samia Riaz', 'samia.riaz@student.edu', 'google_auth', 3);
INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) VALUES ((SELECT MAX(USER_ID) FROM USERS), 'BSSE-2024-012', 33, 23, 2, 2.92);
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) VALUES ('Waleed Shah', 'waleed.shah@student.edu', 'google_auth', 3);
INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) VALUES ((SELECT MAX(USER_ID) FROM USERS), 'BSSE-2024-013', 33, 23, 2, 3.84);
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) VALUES ('Noor Fatima', 'noor.fatima@student.edu', 'google_auth', 3);
INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) VALUES ((SELECT MAX(USER_ID) FROM USERS), 'BSSE-2024-014', 33, 23, 2, 3.61);

-- ── BSCS-1 Section 1A (batch_id=24, section_id=34, dept_id=1) ──
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) VALUES ('Haris Waqar', 'haris.waqar@student.edu', 'google_auth', 3);
INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) VALUES ((SELECT MAX(USER_ID) FROM USERS), 'BSCS-2025-010', 34, 24, 1, 3.95);
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) VALUES ('Laiba Naz', 'laiba.naz@student.edu', 'google_auth', 3);
INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) VALUES ((SELECT MAX(USER_ID) FROM USERS), 'BSCS-2025-011', 34, 24, 1, 3.60);
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) VALUES ('Fahad Mirza', 'fahad.mirza@student.edu', 'google_auth', 3);
INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) VALUES ((SELECT MAX(USER_ID) FROM USERS), 'BSCS-2025-012', 34, 24, 1, 2.85);
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) VALUES ('Sumbul Tauqeer', 'sumbul.tauqeer@student.edu', 'google_auth', 3);
INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) VALUES ((SELECT MAX(USER_ID) FROM USERS), 'BSCS-2025-013', 34, 24, 1, 3.73);
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) VALUES ('Nouman Ali', 'nouman.ali@student.edu', 'google_auth', 3);
INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) VALUES ((SELECT MAX(USER_ID) FROM USERS), 'BSCS-2025-014', 34, 24, 1, 3.88);

-- ── BSCY-4 Section 4A (batch_id=25, section_id=35, dept_id=3) ──
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) VALUES ('Daniyal Hasnain', 'daniyal.hasnain@student.edu', 'google_auth', 3);
INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) VALUES ((SELECT MAX(USER_ID) FROM USERS), 'BSCY-2022-010', 35, 25, 3, 3.76);
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) VALUES ('Tooba Arshad', 'tooba.arshad@student.edu', 'google_auth', 3);
INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) VALUES ((SELECT MAX(USER_ID) FROM USERS), 'BSCY-2022-011', 35, 25, 3, 3.54);
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) VALUES ('Moiz Babar', 'moiz.babar@student.edu', 'google_auth', 3);
INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) VALUES ((SELECT MAX(USER_ID) FROM USERS), 'BSCY-2022-012', 35, 25, 3, 2.78);
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) VALUES ('Bushra Nawab', 'bushra.nawab@student.edu', 'google_auth', 3);
INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) VALUES ((SELECT MAX(USER_ID) FROM USERS), 'BSCY-2022-013', 35, 25, 3, 3.89);
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) VALUES ('Rehan Sohail', 'rehan.sohail@student.edu', 'google_auth', 3);
INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) VALUES ((SELECT MAX(USER_ID) FROM USERS), 'BSCY-2022-014', 35, 25, 3, 3.63);

-- ── BSCY-3 Section 3A (batch_id=26, section_id=36, dept_id=3) ──
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) VALUES ('Zubair Latif', 'zubair.latif@student.edu', 'google_auth', 3);
INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) VALUES ((SELECT MAX(USER_ID) FROM USERS), 'BSCY-2023-010', 36, 26, 3, 3.81);
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) VALUES ('Nimra Javaid', 'nimra.javaid@student.edu', 'google_auth', 3);
INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) VALUES ((SELECT MAX(USER_ID) FROM USERS), 'BSCY-2023-011', 36, 26, 3, 3.59);
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) VALUES ('Fawad Chaudhry', 'fawad.chaudhry@student.edu', 'google_auth', 3);
INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) VALUES ((SELECT MAX(USER_ID) FROM USERS), 'BSCY-2023-012', 36, 26, 3, 2.68);
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) VALUES ('Shanza Aslam', 'shanza.aslam@student.edu', 'google_auth', 3);
INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) VALUES ((SELECT MAX(USER_ID) FROM USERS), 'BSCY-2023-013', 36, 26, 3, 3.74);
INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) VALUES ('Talha Mahmood', 'talha.mahmood@student.edu', 'google_auth', 3);
INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) VALUES ((SELECT MAX(USER_ID) FROM USERS), 'BSCY-2023-014', 36, 26, 3, 3.96);

COMMIT;

SELECT COUNT(*) FROM STUDENTS;
SELECT COUNT(*) FROM USERS;

-- Use PL/SQL blocks to safely capture user_id
DECLARE v_uid NUMBER;
BEGIN
  INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) 
  VALUES ('Ahmed Raza', 'ahmed.raza@student.edu', 'google_auth', 3) 
  RETURNING USER_ID INTO v_uid;
  INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) 
  VALUES (v_uid, 'BSCS-2022-010', 1, 1, 1, 3.85);
END;
/

DECLARE v_uid NUMBER;
BEGIN
  INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) 
  VALUES ('Sara Malik', 'sara.malik@student.edu', 'google_auth', 3) 
  RETURNING USER_ID INTO v_uid;
  INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) 
  VALUES (v_uid, 'BSCS-2022-011', 1, 1, 1, 3.72);
END;
/

DECLARE v_uid NUMBER;
BEGIN
  INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) 
  VALUES ('Usman Tariq', 'usman.tariq@student.edu', 'google_auth', 3) 
  RETURNING USER_ID INTO v_uid;
  INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) 
  VALUES (v_uid, 'BSCS-2022-012', 1, 1, 1, 3.55);
END;
/

DECLARE v_uid NUMBER;
BEGIN
  INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) 
  VALUES ('Fatima Khan', 'fatima.khan@student.edu', 'google_auth', 3) 
  RETURNING USER_ID INTO v_uid;
  INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) 
  VALUES (v_uid, 'BSCS-2022-013', 1, 1, 1, 3.20);
END;
/

DECLARE v_uid NUMBER;
BEGIN
  INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) 
  VALUES ('Ali Hassan', 'ali.hassan@student.edu', 'google_auth', 3) 
  RETURNING USER_ID INTO v_uid;
  INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) 
  VALUES (v_uid, 'BSCS-2022-014', 1, 1, 1, 3.91);
END;
/

DECLARE v_uid NUMBER;
BEGIN
  INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) 
  VALUES ('Zainab Hussain', 'zainab.hussain@student.edu', 'google_auth', 3) 
  RETURNING USER_ID INTO v_uid;
  INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) 
  VALUES (v_uid, 'BSCS-2022-020', 2, 1, 1, 3.78);
END;
/

DECLARE v_uid NUMBER;
BEGIN
  INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) 
  VALUES ('Hassan Shahid', 'hassan.shahid@student.edu', 'google_auth', 3) 
  RETURNING USER_ID INTO v_uid;
  INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) 
  VALUES (v_uid, 'BSCS-2022-021', 2, 1, 1, 3.60);
END;
/

DECLARE v_uid NUMBER;
BEGIN
  INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) 
  VALUES ('Amna Siddiqui', 'amna.siddiqui@student.edu', 'google_auth', 3) 
  RETURNING USER_ID INTO v_uid;
  INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) 
  VALUES (v_uid, 'BSCS-2022-022', 2, 1, 1, 3.95);
END;
/

DECLARE v_uid NUMBER;
BEGIN
  INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) 
  VALUES ('Bilal Ahmed', 'bilal.ahmed@student.edu', 'google_auth', 3) 
  RETURNING USER_ID INTO v_uid;
  INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) 
  VALUES (v_uid, 'BSCS-2022-023', 2, 1, 1, 2.95);
END;
/

DECLARE v_uid NUMBER;
BEGIN
  INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) 
  VALUES ('Hina Baig', 'hina.baig@student.edu', 'google_auth', 3) 
  RETURNING USER_ID INTO v_uid;
  INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) 
  VALUES (v_uid, 'BSCS-2022-024', 2, 1, 1, 3.68);
END;
/

DECLARE v_uid NUMBER;
BEGIN
  INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) 
  VALUES ('Nadia Farooq', 'nadia.farooq@student.edu', 'google_auth', 3) 
  RETURNING USER_ID INTO v_uid;
  INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) 
  VALUES (v_uid, 'BSSE-2022-010', 3, 2, 2, 3.88);
END;
/

DECLARE v_uid NUMBER;
BEGIN
  INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) 
  VALUES ('Omar Sheikh', 'omar.sheikh@student.edu', 'google_auth', 3) 
  RETURNING USER_ID INTO v_uid;
  INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) 
  VALUES (v_uid, 'BSSE-2022-011', 3, 2, 2, 3.52);
END;
/

DECLARE v_uid NUMBER;
BEGIN
  INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) 
  VALUES ('Rabia Noor', 'rabia.noor@student.edu', 'google_auth', 3) 
  RETURNING USER_ID INTO v_uid;
  INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) 
  VALUES (v_uid, 'BSSE-2022-012', 3, 2, 2, 3.75);
END;
/

DECLARE v_uid NUMBER;
BEGIN
  INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) 
  VALUES ('Kamran Iqbal', 'kamran.iqbal@student.edu', 'google_auth', 3) 
  RETURNING USER_ID INTO v_uid;
  INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) 
  VALUES (v_uid, 'BSSE-2022-013', 3, 2, 2, 2.80);
END;
/

DECLARE v_uid NUMBER;
BEGIN
  INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) 
  VALUES ('Sana Javed', 'sana.javed@student.edu', 'google_auth', 3) 
  RETURNING USER_ID INTO v_uid;
  INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) 
  VALUES (v_uid, 'BSSE-2022-014', 3, 2, 2, 3.92);
END;
/

DECLARE v_uid NUMBER;
BEGIN
  INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) 
  VALUES ('Tariq Mehmood', 'tariq.mehmood@student.edu', 'google_auth', 3) 
  RETURNING USER_ID INTO v_uid;
  INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) 
  VALUES (v_uid, 'BSCS-2023-010', 4, 3, 1, 3.65);
END;
/

DECLARE v_uid NUMBER;
BEGIN
  INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) 
  VALUES ('Maira Aziz', 'maira.aziz@student.edu', 'google_auth', 3) 
  RETURNING USER_ID INTO v_uid;
  INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) 
  VALUES (v_uid, 'BSCS-2023-011', 4, 3, 1, 3.80);
END;
/

DECLARE v_uid NUMBER;
BEGIN
  INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) 
  VALUES ('Faisal Rehman', 'faisal.rehman@student.edu', 'google_auth', 3) 
  RETURNING USER_ID INTO v_uid;
  INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) 
  VALUES (v_uid, 'BSCS-2023-012', 4, 3, 1, 2.70);
END;
/

DECLARE v_uid NUMBER;
BEGIN
  INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) 
  VALUES ('Ayesha Qureshi', 'ayesha.qureshi@student.edu', 'google_auth', 3) 
  RETURNING USER_ID INTO v_uid;
  INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) 
  VALUES (v_uid, 'BSCS-2023-013', 4, 3, 1, 3.58);
END;
/

DECLARE v_uid NUMBER;
BEGIN
  INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) 
  VALUES ('Imran Butt', 'imran.butt@student.edu', 'google_auth', 3) 
  RETURNING USER_ID INTO v_uid;
  INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) 
  VALUES (v_uid, 'BSCS-2023-014', 4, 3, 1, 3.71);
END;
/

DECLARE v_uid NUMBER;
BEGIN
  INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) 
  VALUES ('Sadia Perveen', 'sadia.perveen@student.edu', 'google_auth', 3) 
  RETURNING USER_ID INTO v_uid;
  INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) 
  VALUES (v_uid, 'BSSE-2023-010', 29, 21, 2, 3.88);
END;
/

DECLARE v_uid NUMBER;
BEGIN
  INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) 
  VALUES ('Waseem Akram', 'waseem.akram@student.edu', 'google_auth', 3) 
  RETURNING USER_ID INTO v_uid;
  INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) 
  VALUES (v_uid, 'BSSE-2023-011', 29, 21, 2, 3.55);
END;
/

DECLARE v_uid NUMBER;
BEGIN
  INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) 
  VALUES ('Lubna Rashid', 'lubna.rashid@student.edu', 'google_auth', 3) 
  RETURNING USER_ID INTO v_uid;
  INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) 
  VALUES (v_uid, 'BSSE-2023-012', 29, 21, 2, 2.90);
END;
/

DECLARE v_uid NUMBER;
BEGIN
  INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) 
  VALUES ('Adnan Malik', 'adnan.malik@student.edu', 'google_auth', 3) 
  RETURNING USER_ID INTO v_uid;
  INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) 
  VALUES (v_uid, 'BSSE-2023-013', 29, 21, 2, 3.76);
END;
/

DECLARE v_uid NUMBER;
BEGIN
  INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) 
  VALUES ('Rida Zafar', 'rida.zafar@student.edu', 'google_auth', 3) 
  RETURNING USER_ID INTO v_uid;
  INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) 
  VALUES (v_uid, 'BSSE-2023-014', 29, 21, 2, 3.62);
END;
/

DECLARE v_uid NUMBER;
BEGIN
  INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) 
  VALUES ('Zara Hussain', 'zara.hussain@student.edu', 'google_auth', 3) 
  RETURNING USER_ID INTO v_uid;
  INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) 
  VALUES (v_uid, 'BSSE-2023-020', 30, 21, 2, 3.90);
END;
/

DECLARE v_uid NUMBER;
BEGIN
  INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) 
  VALUES ('Hamza Nawaz', 'hamza.nawaz@student.edu', 'google_auth', 3) 
  RETURNING USER_ID INTO v_uid;
  INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) 
  VALUES (v_uid, 'BSSE-2023-021', 30, 21, 2, 3.51);
END;
/

DECLARE v_uid NUMBER;
BEGIN
  INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) 
  VALUES ('Maryam Ilyas', 'maryam.ilyas@student.edu', 'google_auth', 3) 
  RETURNING USER_ID INTO v_uid;
  INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) 
  VALUES (v_uid, 'BSSE-2023-022', 30, 21, 2, 2.65);
END;
/

DECLARE v_uid NUMBER;
BEGIN
  INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) 
  VALUES ('Shahzaib Khan', 'shahzaib.khan@student.edu', 'google_auth', 3) 
  RETURNING USER_ID INTO v_uid;
  INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) 
  VALUES (v_uid, 'BSSE-2023-023', 30, 21, 2, 3.83);
END;
/

DECLARE v_uid NUMBER;
BEGIN
  INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) 
  VALUES ('Iqra Nasir', 'iqra.nasir@student.edu', 'google_auth', 3) 
  RETURNING USER_ID INTO v_uid;
  INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) 
  VALUES (v_uid, 'BSSE-2023-024', 30, 21, 2, 3.69);
END;
/

DECLARE v_uid NUMBER;
BEGIN
  INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) 
  VALUES ('Nabeel Ahmed', 'nabeel.ahmed@student.edu', 'google_auth', 3) 
  RETURNING USER_ID INTO v_uid;
  INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) 
  VALUES (v_uid, 'BSCS-2024-010', 31, 22, 1, 3.77);
END;
/

DECLARE v_uid NUMBER;
BEGIN
  INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) 
  VALUES ('Huma Zubair', 'huma.zubair@student.edu', 'google_auth', 3) 
  RETURNING USER_ID INTO v_uid;
  INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) 
  VALUES (v_uid, 'BSCS-2024-011', 31, 22, 1, 3.56);
END;
/

DECLARE v_uid NUMBER;
BEGIN
  INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) 
  VALUES ('Danish Rauf', 'danish.rauf@student.edu', 'google_auth', 3) 
  RETURNING USER_ID INTO v_uid;
  INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) 
  VALUES (v_uid, 'BSCS-2024-012', 31, 22, 1, 2.88);
END;
/

DECLARE v_uid NUMBER;
BEGIN
  INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) 
  VALUES ('Asma Khalid', 'asma.khalid@student.edu', 'google_auth', 3) 
  RETURNING USER_ID INTO v_uid;
  INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) 
  VALUES (v_uid, 'BSCS-2024-013', 31, 22, 1, 3.93);
END;
/

DECLARE v_uid NUMBER;
BEGIN
  INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) 
  VALUES ('Umar Farooq', 'umar.farooq@student.edu', 'google_auth', 3) 
  RETURNING USER_ID INTO v_uid;
  INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) 
  VALUES (v_uid, 'BSCS-2024-014', 31, 22, 1, 3.64);
END;
/

DECLARE v_uid NUMBER;
BEGIN
  INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) 
  VALUES ('Saima Akhtar', 'saima.akhtar@student.edu', 'google_auth', 3) 
  RETURNING USER_ID INTO v_uid;
  INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) 
  VALUES (v_uid, 'BSCS-2024-020', 32, 22, 1, 3.82);
END;
/

DECLARE v_uid NUMBER;
BEGIN
  INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) 
  VALUES ('Junaid Aslam', 'junaid.aslam@student.edu', 'google_auth', 3) 
  RETURNING USER_ID INTO v_uid;
  INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) 
  VALUES (v_uid, 'BSCS-2024-021', 32, 22, 1, 3.53);
END;
/

DECLARE v_uid NUMBER;
BEGIN
  INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) 
  VALUES ('Mehwish Anwar', 'mehwish.anwar@student.edu', 'google_auth', 3) 
  RETURNING USER_ID INTO v_uid;
  INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) 
  VALUES (v_uid, 'BSCS-2024-022', 32, 22, 1, 2.75);
END;
/

DECLARE v_uid NUMBER;
BEGIN
  INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) 
  VALUES ('Taha Naseem', 'taha.naseem@student.edu', 'google_auth', 3) 
  RETURNING USER_ID INTO v_uid;
  INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) 
  VALUES (v_uid, 'BSCS-2024-023', 32, 22, 1, 3.70);
END;
/

DECLARE v_uid NUMBER;
BEGIN
  INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) 
  VALUES ('Rubab Zaman', 'rubab.zaman@student.edu', 'google_auth', 3) 
  RETURNING USER_ID INTO v_uid;
  INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) 
  VALUES (v_uid, 'BSCS-2024-024', 32, 22, 1, 3.87);
END;
/

DECLARE v_uid NUMBER;
BEGIN
  INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) 
  VALUES ('Areeba Sultan', 'areeba.sultan@student.edu', 'google_auth', 3) 
  RETURNING USER_ID INTO v_uid;
  INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) 
  VALUES (v_uid, 'BSSE-2024-010', 33, 23, 2, 3.79);
END;
/

DECLARE v_uid NUMBER;
BEGIN
  INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) 
  VALUES ('Owais Mirza', 'owais.mirza@student.edu', 'google_auth', 3) 
  RETURNING USER_ID INTO v_uid;
  INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) 
  VALUES (v_uid, 'BSSE-2024-011', 33, 23, 2, 3.57);
END;
/

DECLARE v_uid NUMBER;
BEGIN
  INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) 
  VALUES ('Samia Riaz', 'samia.riaz@student.edu', 'google_auth', 3) 
  RETURNING USER_ID INTO v_uid;
  INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) 
  VALUES (v_uid, 'BSSE-2024-012', 33, 23, 2, 2.92);
END;
/

DECLARE v_uid NUMBER;
BEGIN
  INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) 
  VALUES ('Waleed Shah', 'waleed.shah@student.edu', 'google_auth', 3) 
  RETURNING USER_ID INTO v_uid;
  INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) 
  VALUES (v_uid, 'BSSE-2024-013', 33, 23, 2, 3.84);
END;
/

DECLARE v_uid NUMBER;
BEGIN
  INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) 
  VALUES ('Noor Fatima', 'noor.fatima@student.edu', 'google_auth', 3) 
  RETURNING USER_ID INTO v_uid;
  INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) 
  VALUES (v_uid, 'BSSE-2024-014', 33, 23, 2, 3.61);
END;
/

DECLARE v_uid NUMBER;
BEGIN
  INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) 
  VALUES ('Haris Waqar', 'haris.waqar@student.edu', 'google_auth', 3) 
  RETURNING USER_ID INTO v_uid;
  INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) 
  VALUES (v_uid, 'BSCS-2025-010', 34, 24, 1, 3.95);
END;
/

DECLARE v_uid NUMBER;
BEGIN
  INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) 
  VALUES ('Laiba Naz', 'laiba.naz@student.edu', 'google_auth', 3) 
  RETURNING USER_ID INTO v_uid;
  INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) 
  VALUES (v_uid, 'BSCS-2025-011', 34, 24, 1, 3.60);
END;
/

DECLARE v_uid NUMBER;
BEGIN
  INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) 
  VALUES ('Fahad Mirza', 'fahad.mirza@student.edu', 'google_auth', 3) 
  RETURNING USER_ID INTO v_uid;
  INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) 
  VALUES (v_uid, 'BSCS-2025-012', 34, 24, 1, 2.85);
END;
/

DECLARE v_uid NUMBER;
BEGIN
  INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) 
  VALUES ('Sumbul Tauqeer', 'sumbul.tauqeer@student.edu', 'google_auth', 3) 
  RETURNING USER_ID INTO v_uid;
  INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) 
  VALUES (v_uid, 'BSCS-2025-013', 34, 24, 1, 3.73);
END;
/

DECLARE v_uid NUMBER;
BEGIN
  INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) 
  VALUES ('Nouman Ali', 'nouman.ali@student.edu', 'google_auth', 3) 
  RETURNING USER_ID INTO v_uid;
  INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) 
  VALUES (v_uid, 'BSCS-2025-014', 34, 24, 1, 3.88);
END;
/

DECLARE v_uid NUMBER;
BEGIN
  INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) 
  VALUES ('Daniyal Hasnain', 'daniyal.hasnain@student.edu', 'google_auth', 3) 
  RETURNING USER_ID INTO v_uid;
  INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) 
  VALUES (v_uid, 'BSCY-2022-010', 35, 25, 3, 3.76);
END;
/

DECLARE v_uid NUMBER;
BEGIN
  INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) 
  VALUES ('Tooba Arshad', 'tooba.arshad@student.edu', 'google_auth', 3) 
  RETURNING USER_ID INTO v_uid;
  INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) 
  VALUES (v_uid, 'BSCY-2022-011', 35, 25, 3, 3.54);
END;
/

DECLARE v_uid NUMBER;
BEGIN
  INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) 
  VALUES ('Moiz Babar', 'moiz.babar@student.edu', 'google_auth', 3) 
  RETURNING USER_ID INTO v_uid;
  INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) 
  VALUES (v_uid, 'BSCY-2022-012', 35, 25, 3, 2.78);
END;
/

DECLARE v_uid NUMBER;
BEGIN
  INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) 
  VALUES ('Bushra Nawab', 'bushra.nawab@student.edu', 'google_auth', 3) 
  RETURNING USER_ID INTO v_uid;
  INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) 
  VALUES (v_uid, 'BSCY-2022-013', 35, 25, 3, 3.89);
END;
/

DECLARE v_uid NUMBER;
BEGIN
  INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) 
  VALUES ('Rehan Sohail', 'rehan.sohail@student.edu', 'google_auth', 3) 
  RETURNING USER_ID INTO v_uid;
  INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) 
  VALUES (v_uid, 'BSCY-2022-014', 35, 25, 3, 3.63);
END;
/

DECLARE v_uid NUMBER;
BEGIN
  INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) 
  VALUES ('Zubair Latif', 'zubair.latif@student.edu', 'google_auth', 3) 
  RETURNING USER_ID INTO v_uid;
  INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) 
  VALUES (v_uid, 'BSCY-2023-010', 36, 26, 3, 3.81);
END;
/

DECLARE v_uid NUMBER;
BEGIN
  INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) 
  VALUES ('Nimra Javaid', 'nimra.javaid@student.edu', 'google_auth', 3) 
  RETURNING USER_ID INTO v_uid;
  INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) 
  VALUES (v_uid, 'BSCY-2023-011', 36, 26, 3, 3.59);
END;
/

DECLARE v_uid NUMBER;
BEGIN
  INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) 
  VALUES ('Fawad Chaudhry', 'fawad.chaudhry@student.edu', 'google_auth', 3) 
  RETURNING USER_ID INTO v_uid;
  INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) 
  VALUES (v_uid, 'BSCY-2023-012', 36, 26, 3, 2.68);
END;
/

DECLARE v_uid NUMBER;
BEGIN
  INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) 
  VALUES ('Shanza Aslam', 'shanza.aslam@student.edu', 'google_auth', 3) 
  RETURNING USER_ID INTO v_uid;
  INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) 
  VALUES (v_uid, 'BSCY-2023-013', 36, 26, 3, 3.74);
END;
/

DECLARE v_uid NUMBER;
BEGIN
  INSERT INTO USERS (FULL_NAME, EMAIL, PASSWORD_HASH, ROLE_ID) 
  VALUES ('Talha Mahmood', 'talha.mahmood@student.edu', 'google_auth', 3) 
  RETURNING USER_ID INTO v_uid;
  INSERT INTO STUDENTS (USER_ID, REG_NUMBER, SECTION_ID, BATCH_ID, DEPT_ID, CGPA) 
  VALUES (v_uid, 'BSCY-2023-014', 36, 26, 3, 3.96);
END;
/

COMMIT;

-- Delete users that have no matching student record (orphaned from failed inserts)
DELETE FROM USERS 
WHERE EMAIL LIKE '%@student.edu' 
AND USER_ID NOT IN (SELECT USER_ID FROM STUDENTS);

COMMIT;

SELECT COUNT(*) FROM USERS WHERE EMAIL LIKE '%@student.edu';
SELECT COUNT(*) FROM STUDENTS;

BEGIN generate_dean_list('Fall-2025'); END;
/
BEGIN generate_dean_list('Spring-2026'); END;
/

-- Check Dean's List entries
SELECT 
  (SELECT COUNT(*) FROM STUDENTS) AS total_students,
  (SELECT COUNT(*) FROM DEAN_LIST) AS total_dean_list,
  (SELECT COUNT(*) FROM PROJECTS) AS total_projects,
  (SELECT COUNT(*) FROM AUDIT_LOGS) AS total_audit_logs,
  (SELECT COUNT(*) FROM CGPA_RECORDS) AS total_cgpa_records
FROM DUAL;

